import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Bokor } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.className} ${geistMono.variable} overflow-x-hidden antialiased `}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
